[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2
    
[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/patrickklaeren"
    weight = 3